services:
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: development_password
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:16.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'development_password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: manager
