services:
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/filter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: development_password
    depends_on:
      - db

  db:
    image: postgres:17.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'development_password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: filter
