spring:
  application.name: Highload Stream Proccessor
  jpa:
    show_sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: validate
  kafka:
    consumer:
      group-id: filter_service
      enable-auto-commit: true
    admin.auto-create: true

filter:
  listen-to: source
  send-to: filtered
